### ISSUE TITLE
Do mod Codes work with this?

### ISSUE THREAD

**Issue by DTK21** [PTKickass/ForcesModInstaller#2]
I know the last update was in 2018 but I noticed how the readme mentions in the mod.ini is
[Main]
IncludeDir0="."
IncludeDirCount=1

But most game changing mods come with .hmm codes and even when the mod's .ini has the code listed I assumed maybe this installer didn't take that into account and most likely Config ini's for the same reason
Managed to get Sonic Forces Overclocked working but the code inside the folder that allowed for Ring's to add boost wasn't working and whatever else listed in the OverclockedCodes.hmm even though the Mod's ini was
[Desc]
Author="Overclocked Team"
Title="Sonic Forces Overclocked"
Version=1.0
Description="A story-based continuation of Sonic Forces, featuring rebuilt levels, new cutscenes and more.\n\nWhen Neo Metal Sonic and Infinite forge an alliance to eliminate the Resistance using overclocked Phantom Rubies, Sonic and friends must fight to take back the world once more."
Date="2023-03-26"
AuthorURL=""

[Main]
UpdateServer=""
SaveFile="savedata/savedata.xml"
ID="5762628D"
IncludeDir0="."
IncludeDirCount=1
DependsCount=0
DLLFile=""
CodeFile="OverclockedCodes.hmm"
ConfigSchemaFile="ConfigSchema.json"

Also had to just move directory files all into one and change the format to be install friendly but just the code file got left out

**Comment by PTKay** [comment]
This is a mod installer, not a mod loader. All it does is pack files into the game's CPK archive, so .HMM and .DLL files do not work. Use HedgeModManager for that.
